[package]
name = "dulovar-p2p"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
iroh = "0.92.0"
futures_rand = { package = "rand", version = "0.8.0" }
reqwest = "0.12.23"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
