use std::error::Error;

// Declaration and inclusion of code generated by tonic-build
pub mod alert {
    include!("grpc_daemon/alert.rs");
}

mod grpc_daemon;
mod orchestrator;
mod p2p_kad;
use orchestrator::run_concurrent_services;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    run_concurrent_services().await?;

    Ok(())
}
