-- Migration number: 0001 	 2025-10-15T20:52:35.015Z
CREATE TABLE nodes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  address TEXT NOT NULL UNIQUE,
  valid BOOLEAN NOT NULL DEFAULT FALSE,
  master BOOLEAN NOT NULL DEFAULT FALSE
);
